### ISSUE TITLE
add material citation UUID to treatment export

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatments-xml#11]
@gsautter can you please add materialCitation UUID to the XML export to treatments-xml.

This is relevant for solving this use case https://github.com/plazi/names_LOD/issues/133

**Comment by myrmoteras** [comment]
@retog @nleanba  if this is necessary to get the UUID, all the treatments need to be pushed again-

It will double the data volume in Github?!

Worthwhile?

**Comment by myrmoteras** [comment]
the PURL for material citation is https://tb.plazi.org/GgServer/dwcaRecords/03E96421FFE05F47BF1BFC24FA76CC28.mc.3B28DF6AFFE05F48BF85FBECFD49CEDF

**Comment by myrmoteras** [comment]
@retog if you insert URLs like this, then you need to tell Guido to allow to resolve the mc in Frankfurt and it will resolve to mat-cit.plazi.org

**Comment by nleanba** [comment]
I don‘t think this will actually double the amount of data Github stores, as I expect them to make use of (some) de-duplication / diffs.

**Comment by nleanba** [comment]
once the uuid are here, the URI for a material-citation is:

`https://tb.plazi.org/GgServer/dwcaRecords/{treatment uuid}.mc.{material citation uuid}`

(clickable links (synospecies) can/should link to `https://treatment.plazi.org/id/{treatment uuid}#{material citation uuid}`)

~TODO @​nleanba handle this in gg2rdf XSLT~
https://github.com/plazi/gg2rdf/releases/tag/v1.5 implements these resource urls (if id is present; fallback to current frankenstein-urls otherwise)

**Comment by nleanba** [comment]
@gsautter

It would be much appreciated if you reconfigure the export to treatments-xml (this repo) as to include the UUIDs of the MaterialsCitations for all future exports.

Preferrably _without_ a full re-export, as to not overload the transformation.

**Comment by myrmoteras** [comment]
@gsautter can we finish this issue - may be add this to the batch? For now it would be helpful to make this for new treatments, as well as for the Flora der Schweiz: https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+bib.author+bib.title&groupingFields=doc.articleUuid+bib.author+bib.title&FP-bib.author=%22%25Hirzel%25%22&FP-bib.title=%22Flora%20der%20Schweiz%25%22&format=HTML or in [JSON ](https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+bib.author+bib.title&groupingFields=doc.articleUuid+bib.author+bib.title&FP-bib.author=%22%25Hirzel%25%22&FP-bib.title=%22Flora%20der%20Schweiz%25%22&format=JSON)

tx

**Comment by gsautter** [comment]
The exporter is adjusted to export the annotation UUIDs, and a re-export for "Flora der Schweiz" is running now ... let's see how much havoc this mass update wreaks to the Git repo.

**Comment by gsautter** [comment]
Seems to be working, see for example https://github.com/plazi/treatments-xml/blob/main/data/00/69/E4/0069E4811D69FE49F29FFB1B2DB3B2C0.xml

**Comment by gsautter** [comment]
Which other treatments (apart from "Flora der Schweiz") should be force-updated?

**Comment by retog** [comment]
> Which other treatments (apart from "Flora der Schweiz") should be force-updated?

I think all treatments where the XML used to be incomplete. @nleanba ?

**Comment by myrmoteras** [comment]
HBMW https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&groupingFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&FP-bib.source=%22%25Handbook%20of%20the%20Ma%25%22&format=HTML or https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&groupingFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&FP-bib.source=%22%25Handbook%20of%20the%20Ma%25%22&format=CSV&separator=%2C

**Comment by myrmoteras** [comment]
https://tb.plazi.org/GgServer/html/8B88FAA8AA092E66D4A43721811A6260

https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&groupingFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&FP-bib.source=%22%25ammal%20Species%25%22&format=HTML  or https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&groupingFields=doc.articleUuid+bib.author+bib.title+bib.source+bib.volume&FP-bib.source=%22%25ammal%20Species%25%22&format=CSV&separator=%2C

**Comment by nleanba** [comment]
As far as I can tell, this is done(?)
