### ISSUE TITLE
Advertised SPARQL endpoint does not appear to be public

### ISSUE THREAD

**Issue by hlapp** [plazi/treatments-xml#12]
Attempts to query the advertised SPARQL endpoint at https://treatment.ld.plazi.org/sparql results in a 403 error. Is this intentional (in which case this should be stated in the README).

**Comment by hlapp** [comment]
It seems that there is a public endpoint here: https://lindas.admin.ch/query Should this be advertised instead?

**Comment by retog** [comment]
Hi @hlapp, the https://treatment.ld.plazi.org/sparql endpoint is public, and I don't see why you got a 403 response. Could you paste the full request you make that leads to the 403 response?

We monitor the endpoint by running a moderately complex query via a Github action. The success rate and status is published here: https://plazi.github.io/monitoring/

More precisely here: https://plazi.github.io/monitoring/history/ld-plazi-kingdoms

**Comment by retog** [comment]
A recent downtime was addressed with and documented by this issue: https://github.com/plazi/monitoring/issues/10 but the response code was not a `403`

**Comment by hlapp** [comment]
@retog I was using [Yasgui](https://yasgui.triply.cc). I just tried again, and the error now is a 405. It seems that by default the method used by Yasgui is POST. When I switched it to GET, it indeed started working!

Any reason not to enable POST? If yes, then perhaps add a short note that one should make sure to use HTTP GET as method.

**Comment by retog** [comment]
@hlapp the limitation to GET is a "poor man's" access control to prevent INSERT/DELETE statement being run. This became necessary when we started using blazegraph which doesn't easily allow exposing a read-only endpoint (see https://github.com/blazegraph/database/issues/150)

Where would you suggest adding that note? Having it on https://synospecies.plazi.org/settings would be potentially confusing as this has no relevance in synospecies which only uses `GET`.

**Comment by balhoff** [comment]
@retog, @hlapp pointed me here regarding read-only Blazegraph. It is pretty straightforward to run read-only if you don't need to allow update at all. We have a Docker image for running Blazegraph which demonstrates what's needed: https://github.com/phenoscape/blazegraph-docker (sorry, the repo isn't really documented). The main thing is to pass a custom web.xml using, e.g. `-Djetty.overrideWebXml=custom.xml`. In that file you can set Blazegraph to be read-only (https://github.com/phenoscape/blazegraph-docker/blob/d2d24cabe19796ba52b94c3add083475aebe5d2c/readonly_cors.xml#L6-L10)

**Comment by hlapp** [comment]
> Where would you suggest adding that note?

@retog I posted a suggestion here: https://github.com/plazi/treatments-rdf/pull/11

**Comment by retog** [comment]
@hlapp thanks, merged.

@balhoff the (code that keeps the triple store in sync with the repo)[https://github.com/plazi/turtle-hook/blob/main/src/main.ts] needs sparql-update.
