### ISSUE TITLE
Failing Actions

### ISSUE THREAD

**Issue by retog** [plazi/treatments-xml#14]
Actions were failing due to lack of space. Moved action to a group with a large runner. So now having a new kind of failure: https://github.com/plazi/treatments-xml/actions/runs/5918131951

**Comment by retog** [comment]
Mayve with a change generating different RDF it will succeed, so aiting for the next data change.

**Comment by nleanba** [comment]
Since https://github.com/plazi/treatments-xml/commit/122203ec1edcacd9c35355857008ae076b0223f9, no action has succeded

**Comment by nleanba** [comment]
It seems to fail within tj-actions/changed-files

**Comment by nleanba** [comment]
I tried to update gg2rdf to a newer version of changed-files, we’ll see if it work on the next XML update

However, we need to make a full update now? as treatments-rdf is now weeks out of date!

**Comment by nleanba** [comment]
@retog can you trigger a full update of treatments-rdf?

**Comment by nleanba** [comment]
/fastssd/actions-runner/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /fastssd/actions-runner/externals/node20/bin/node)

what is this and can you fix it? (from action log)

**Comment by retog** [comment]
It seems ubuntu 18.04 comes with GLBC_2.27. I'm now trying to upgrade the distribution. It's weird as Github runner claim to r equire ubuntu 16.04 or  higher.

**Comment by retog** [comment]
So after the update we get a new error!

> ERROR: Can't find local .git directory. Please run actions/checkout before this action

**Comment by retog** [comment]
@nleanba could the new  error be related to the update of `tj-actions/changed-files` in gg2rdf?

**Comment by nleanba** [comment]
It's probably related, however as far as I can tell, the usage (so far we need it) of `tj-actions/changed-files` hasn't changed

can you try if the action runs on a normal (github) runner? (ignoring space problems)
