### ISSUE TITLE
suggest to use GitHub -> Zenodo integration to publish treatment-xml releases to Zenodo

### ISSUE THREAD

**Issue by jhpoelen** [plazi/treatments-xml#6]
Having your valuable data in two places would make it easier for me to sleep at night. . .  ; ) 

@myrmoteras @gsautter

**Comment by retog** [comment]
This could be easily implemented with the zenodo GitHub integration as in https://github.com/plazi/treatments-rdf/issues/1#issuecomment-713585263. But if I'm not mistaken all these XML documents are already uploaded to zenodo by the [treatment-bank](https://github.com/plazi/treatmentBank). @gsautter, can you confirm this?

**Comment by jhpoelen** [comment]
Is making releases of treatments-xml repository still on your radar?

**Comment by myrmoteras** [comment]
Horror, don't understand. Treatment-xml is an automated processe

New species of the day<https://tb.plazi.org/GgServer/static/newToday.html>
________________________________

**Comment by jhpoelen** [comment]
The idea is to create releases of treatment-xml that are also published (in batch) via Zenodo at some suitable interval (one release per 6 months perhaps?). This way, you'd make it easier for folks like me to reference and re-use specific versions of treatment-xml .

**Comment by jhpoelen** [comment]
To avoid losing track of specific versions of Plazi's Treatment XML corpora , I created a versioned archive of the https://github.com/plazi/treatments-xml . Hopefully, I can replace my own copy with an "official" Plazi copy.

Plazi Community. (2022). Plazi Treatments XML Archive hash://sha256/3cfd60b8b19e76d208377537835de92efdb5b945a6a71765b74ed2fe22298b42 hash://md/594923284e3eb9965b8cbad149c76cd0f (hash://sha256/3cfd60b8b19e76d208377537835de92efdb5b945a6a71765b74ed2fe22298b42) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7443343

**Comment by retog** [comment]
The zenodo plugin is now enabled. Feel free to open an issue, whenever you would like us to create a tag.

**Comment by jhpoelen** [comment]
@retog thank you for enabling the Github<>Zenodo integration for plazi/treatments-xml . I'll try and remember to open an issue when I'd like to create a tag.
