### ISSUE TITLE
suspected typo in 194287C9FF8CBA20B482F5FEB6BEF840 - "Tadarida latouchet" it should be "Tadarida latouchei"

### ISSUE THREAD

**Issue by jhpoelen** [plazi/treatments-xml#7]
In discussion with @ajacsherman - we noticed a suspected typo in: 

194287C9FF8CBA20B482F5FEB6BEF840

instead of "Tadarida latouchet" it should be "Tadarida latouchei"

Aja checked in the original.

194287C9FF8CBA20B482F5FEB6BEF840,"Handbook of the Mammals of the World – Volume 9 Bats, Barcelona: Lynx Edicions",978-84-16728-19-0,hbmw_9_Molossidae_598.pdf.imf,hash://md5/e57bffb1ffbcba10b412f760b226ffce,667,zip:hash://sha256/ec5fd314a06aba1a7b0b72f23e54ac625ae272bd98f82f1d01f4c09627d9e8e0!/treatments-xml-main/data/19/42/87/194287C9FF8CBA20B482F5FEB6BEF840.xml,Tadarida latouchet,Tadarida,latouchet,Thomas,1920,Tadaride de La Touche @fr | La-Touche-Bulldogfledermaus @de | Murciélago rabudo de La Touche @es,"7 Tadarida latouchet Thomas, 1920 , “Chin-wang-tao, N.E. Chihli, China .” ladarida latouchei was previously considered a subspecies of 1. teniotis; currently recognized as a distinct species, but further revision is needed. Monotypic.","Disjunct locations in NE China ( Liaoning , Inner Mongolia [= Nei Mongol ], Hebei , Beijing , and Shandong ), N & C Laos , and NE Thailand ( Loei Province ). There are three vagrant records in Japan , on Amami-Oshima, Kuchinoerabujima, and Yoronjima Is.","Head—-body 67-72 mm , tail 41-49 mm , ear 22-27 mm , forearm 53-57 mm . No specific data are available for hindfoot length or body weight. Hairs are short, soft and velvety; dorsal fur is dark brown or grayish brown; ventralside is paler. Upperlip is wrinkled. Ears are large andjoined by a flap of narrow skin over forehead. Wing membrane is attached to basal one-third oftibia.","In Thailand , La Touche’s Free-tailed Bat has been recorded in dry evergreen hill forest at 1500 m .",No information.,No information.,La Touche’s Free-tailed Bat is known to roost in caves.,[La Touche’s Free-tailed Bat was recorded forming a large colony in Laos .,Classified as Data Deficient on The IUCN Red List. Population size 1s decreasing and La Touche’s Free-tailed Bat is thought to be at risk due to hunting for food and roost disturbance.,Abe et al. (2005) | Corbet & Hill (1992) | Francis (2008a) | Francis & Maeda (2008) | Funakoshi & Kunisaki (2000) | Kock (1999) | Simmons (2005) | Smith & Xie Yan (2008) | Wang Yingxiang (2003),https://zenodo.org/record/6567934/files/figure.png,"113. La Touche’s Free-tailed Bat Tadarida latouchet French: Tadaride de La Touche / German: La-Touche-Bulldogfledermaus / Spanish: Murciélago rabudo de La Touche Taxonomy. 7 Tadarida latouchet Thomas, 1920 , “Chin-wang-tao, N.E. Chihli, China .” ladarida latouchei was previously considered a subspecies of 1. teniotis; currently recognized as a distinct species, but further revision is needed. Monotypic. Distribution. Disjunct locations in NE China ( Liaoning , Inner Mongolia [= Nei Mongol ], Hebei , Beijing , and Shandong ), N & C Laos , and NE Thailand ( Loei Province ). There are three vagrant records in Japan , on Amami-Oshima, Kuchinoerabujima, and Yoronjima Is. Descriptive notes. Head—-body 67-72 mm , tail 41-49 mm , ear 22-27 mm , forearm 53-57 mm . No specific data are available for hindfoot length or body weight. Hairs are short, soft and velvety; dorsal fur is dark brown or grayish brown; ventralside is paler. Upperlip is wrinkled. Ears are large andjoined by a flap of narrow skin over forehead. Wing membrane is attached to basal one-third oftibia. Habitat. In Thailand , La Touche’s Free-tailed Bat has been recorded in dry evergreen hill forest at 1500 m . Food and Feeding. No information. Breeding. No information. Activity patterns. La Touche’s Free-tailed Bat is known to roost in caves. Movements, Home range and Social organization. [La Touche’s Free-tailed Bat was recorded forming a large colony in Laos . Status and Conservation. Classified as Data Deficient on The IUCN Red List. Population size 1s decreasing and La Touche’s Free-tailed Bat is thought to be at risk due to hunting for food and roost disturbance. Bibliography. Abe et al. (2005), Corbet & Hill (1992), Francis (2008a), Francis & Maeda (2008), Funakoshi & Kunisaki (2000), Kock (1999), Simmons (2005), Smith & Xie Yan (2008), Wang Yingxiang (2003)."

**Comment by flsimoes** [comment]
Fixed.
It was indeed an OCR misread

**Comment by jhpoelen** [comment]
@flsimoes thanks! I just verified that https://github.com/jhpoelen/hmw/releases/tag/0.4 contains the fixed name.
