### ISSUE TITLE
failed to load latest commit

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatments-xml#8]
when looking for https://tb.plazi.org/GgServer/html/03D087AEFFC9FF84FEF4034CFC2AF6CC in this directory https://github.com/plazi/treatments-xml/tree/main/data/03/D0/87 I got this error message

![image](https://user-images.githubusercontent.com/4609956/199922143-0f6046e6-68ec-4351-ba73-bf86e1aa68f3.png)

**Comment by nleanba** [comment]
https://github.com/plazi/treatments-xml/blob/main/data/03/D0/87/03D087AEFFC9FF84FEF4034CFC2AF6CC.xml
